stages:
  - prepare
  - test
  - deploy

prepare:
  stage: prepare
  image: registry.gitlab.com/path/to/private/image
  cache:
    key: $CI_COMMIT_REF_SLUG
    paths:
      - vendor/
      - var/cache/
  script:
    - composer install

cs_fixer:
  stage: test
  needs:
    - prepare
  image: php:8.1.6
  cache:
    key: $CI_COMMIT_REF_SLUG
    paths:
      - vendor/
      - var/cache/
    policy: pull
  script:
    - php -d memory_limit=2G vendor/bin/php-cs-fixer fix --dry-run

phpstan:
  stage: test
  needs:
    - prepare
  image: php:8.1.6
  cache:
    key: $CI_COMMIT_REF_SLUG
    paths:
      - vendor/
      - var/cache/
    policy: pull
  script:
    - php -d memory_limit=2G vendor/bin/phpstan analyse

deploy:
  stage: deploy
  needs:
    - cs_fixer
    - phpstan
  image: damlox/deployer:7.0.2
  cache:
    key: $CI_COMMIT_REF_SLUG
    paths:
      - vendor/
    policy: pull
  before_script:
    - mkdir -p ~/.ssh
    - eval $(ssh-agent -s)
    - echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - echo "$SSH_PRIVATE_KEY" | base64 -d | tr -d '\r' | ssh-add - > /dev/null
  script:
    - php -d memory_limit=-1 /usr/local/bin/dep deploy -vvv
  resource_group: production
  only:
    - master
  when: manual
