# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    _instanceof:
        App\Rubix\Algorithm\AlgorithmInterface:
            tags:
                - 'app.algorithm'
        App\Rubix\Kernel\KernelInterface:
            tags:
                - 'app.kernel'
        App\Rubix\Transformer\TransformerInterface:
            tags:
                - 'app.transformer'

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Kernel.php'

    App\Util\Training\ModelTraining:
        arguments:
            $trainingPath: '%env(TRAINING_PATH)%'

    App\Util\Predict\ModelPredict:
        arguments:
            $trainingPath: '%env(TRAINING_PATH)%'

    App\Rubix\AlgorithmSelector:
        arguments:
            $algorithms: !tagged_iterator app.algorithm
    App\Rubix\TransformerSelector:
        arguments:
            $transformers: !tagged_iterator app.transformer
    App\Rubix\ParameterDecoder:
        arguments:
            $kernels: !tagged_iterator app.kernel
            $algorithms: !tagged_iterator app.algorithm
